/*
 * FrameMain.java
 *
 * Created on __DATE__, __TIME__
 */

package com.orilore.ui;

import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;

import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;

/**
 *
 * @author  __USER__
 */
public class FrameMain extends javax.swing.JFrame {
	private static final long serialVersionUID = 1L;

	/** Creates new form FrameMain */
	public FrameMain() {
		initComponents();
		this.setTitle("JDBC Artifact");
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	@SuppressWarnings({ "unchecked", "rawtypes", "serial" })
	private void initComponents() {

		spTables = new javax.swing.JScrollPane();
		lstTables = new javax.swing.JList();
		jpOption = new javax.swing.JPanel();
		btnCreate = new javax.swing.JButton();
		jLabel4 = new javax.swing.JLabel();
		lstDB = new javax.swing.JComboBox();
		jLabel5 = new javax.swing.JLabel();
		txUrl = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		txUid = new javax.swing.JTextField();
		jLabel7 = new javax.swing.JLabel();
		txPwd = new javax.swing.JTextField();
		btnConnect = new javax.swing.JButton();
		btnSave = new javax.swing.JButton();
		jTabbedPane1 = new javax.swing.JTabbedPane();
		jPanel2 = new javax.swing.JPanel();
		cbPojo = new javax.swing.JCheckBox();
		jLabel1 = new javax.swing.JLabel();
		txPojo = new javax.swing.JTextField();
		cbDao = new javax.swing.JCheckBox();
		jLabel2 = new javax.swing.JLabel();
		txDao = new javax.swing.JTextField();
		cbBiz = new javax.swing.JCheckBox();
		jLabel3 = new javax.swing.JLabel();
		txBiz = new javax.swing.JTextField();
		jPanel3 = new javax.swing.JPanel();
		cbPojo1 = new javax.swing.JCheckBox();
		jLabel9 = new javax.swing.JLabel();
		txPojo1 = new javax.swing.JTextField();
		cbDao1 = new javax.swing.JCheckBox();
		jLabel10 = new javax.swing.JLabel();
		txDao1 = new javax.swing.JTextField();
		cbBiz1 = new javax.swing.JCheckBox();
		jLabel11 = new javax.swing.JLabel();
		txBiz1 = new javax.swing.JTextField();
		cbBiz2 = new javax.swing.JCheckBox();
		jLabel12 = new javax.swing.JLabel();
		txBiz2 = new javax.swing.JTextField();
		spInfo = new javax.swing.JScrollPane();
		txInfo = new javax.swing.JTextArea();
		jPanel1 = new javax.swing.JPanel();
		jLabel8 = new javax.swing.JLabel();
		labUrl = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setResizable(false);

		spTables.setBorder(javax.swing.BorderFactory.createTitledBorder(
				javax.swing.BorderFactory.createEtchedBorder(),
				"\u6570\u636e\u8868",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
				javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 14)));

		lstTables.setBackground(javax.swing.UIManager.getDefaults().getColor(
				"Button.background"));
		lstTables.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12));
		lstTables.setModel(new javax.swing.AbstractListModel() {
			String[] strings = {};

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});
		spTables.setViewportView(lstTables);

		jpOption.setBorder(javax.swing.BorderFactory.createTitledBorder(
				javax.swing.BorderFactory.createEtchedBorder(),
				"\u751f\u6210\u9009\u9879",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
				javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 14)));

		btnCreate.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12));
		btnCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/javax/swing/plaf/metal/icons/ocean/hardDrive.gif"))); // NOI18N
		btnCreate.setText("\u751f\u6210");
		btnCreate.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnCreateActionPerformed(evt);
			}
		});

		jLabel4.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12));
		jLabel4.setText("\u6570\u636e\u5e93");

		lstDB.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12));
		lstDB.setModel(new javax.swing.DefaultComboBoxModel(dbs));
		lstDB.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				lstDBActionPerformed(evt);
			}
		});

		jLabel5.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12));
		jLabel5.setText("URL");

		txUrl.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12));

		jLabel6.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12));
		jLabel6.setText("\u7528\u6237\u540d");

		txUid.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12));

		jLabel7.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12));
		jLabel7.setText("\u5bc6\u7801");

		txPwd.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12));

		btnConnect.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12));
		btnConnect.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/javax/swing/plaf/metal/icons/ocean/collapsed.gif"))); // NOI18N
		btnConnect.setText("\u8fde\u63a5");
		btnConnect.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnConnectActionPerformed(evt);
			}
		});

		btnSave.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12));
		btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/javax/swing/plaf/metal/icons/ocean/floppy.gif"))); // NOI18N
		btnSave.setText("\u5b58\u50a8\u8bbe\u7f6e");
		btnSave.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSaveActionPerformed(evt);
			}
		});

		cbPojo.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12));
		cbPojo.setSelected(true);
		cbPojo.setText("\u751f\u6210POJO");
		cbPojo.setEnabled(false);

		jLabel1.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12));
		jLabel1.setText("Package");

		txPojo.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12));
		txPojo.setText("com.orilore.entitys");
		txPojo.setToolTipText("\u8bf7\u8f93\u5165\u5b8c\u6574\u5305\u540d");

		cbDao.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12));
		cbDao.setSelected(true);
		cbDao.setText("\u751f\u6210\u6301\u4e45\u5c42\u4ee3\u7801");

		jLabel2.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12));
		jLabel2.setText("Package");

		txDao.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12));
		txDao.setText("com.orilore.dao");
		txDao.setToolTipText("\u8bf7\u8f93\u5165\u5b8c\u6574\u5305\u540d");

		cbBiz.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12));
		cbBiz.setSelected(true);
		cbBiz.setText("\u751f\u6210\u4e1a\u52a1\u5c42\u4ee3\u7801");
		cbBiz.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cbBizActionPerformed(evt);
			}
		});

		jLabel3.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12));
		jLabel3.setText("Package");

		txBiz.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12));
		txBiz.setText("com.orilore.biz");
		txBiz.setToolTipText("\u8bf7\u8f93\u5165\u5b8c\u6574\u5305\u540d");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel2Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel2Layout
																										.createSequentialGroup()
																										.addContainerGap()
																										.addComponent(
																												jLabel3)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																												24,
																												Short.MAX_VALUE))
																						.addGroup(
																								jPanel2Layout
																										.createSequentialGroup()
																										.addContainerGap()
																										.addComponent(
																												jLabel2)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
																						.addGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								jPanel2Layout
																										.createSequentialGroup()
																										.addGroup(
																												jPanel2Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addGroup(
																																jPanel2Layout
																																		.createSequentialGroup()
																																		.addContainerGap()
																																		.addComponent(
																																				jLabel1,
																																				0,
																																				0,
																																				Short.MAX_VALUE))
																														.addComponent(
																																cbPojo))
																										.addGap(2,
																												2,
																												2)))
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(
																								txBiz)
																						.addComponent(
																								txDao)
																						.addComponent(
																								txPojo,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								182,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGap(39,
																				39,
																				39))
														.addComponent(
																cbDao,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																117,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(cbBiz))
										.addContainerGap()));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addComponent(cbPojo)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1)
														.addComponent(
																txPojo,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(cbDao)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel2)
														.addComponent(
																txDao,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(cbBiz)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel3)
														.addComponent(
																txBiz,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(62, Short.MAX_VALUE)));

		jTabbedPane1.addTab("JDBC", jPanel2);

		cbPojo1.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12));
		cbPojo1.setSelected(true);
		cbPojo1.setText("\u751f\u6210POJO");
		cbPojo1.setEnabled(false);

		jLabel9.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12));
		jLabel9.setText("Package");

		txPojo1.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12));
		txPojo1.setText("com.orilore.model");
		txPojo1.setToolTipText("\u8bf7\u8f93\u5165\u5b8c\u6574\u5305\u540d");

		cbDao1.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12));
		cbDao1.setSelected(true);
		cbDao1.setText("\u751f\u6210Mapper\u6587\u4ef6");

		jLabel10.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12));
		jLabel10.setText("Package");

		txDao1.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12));
		txDao1.setText("com.orilore.model");
		txDao1.setToolTipText("\u8bf7\u8f93\u5165\u5b8c\u6574\u5305\u540d");

		cbBiz1.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12));
		cbBiz1.setSelected(true);
		cbBiz1.setText("\u751f\u6210Mapper\u63a5\u53e3");

		jLabel11.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12));
		jLabel11.setText("Package");

		txBiz1.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12));
		txBiz1.setText("com.orilore.mapper");
		txBiz1.setToolTipText("\u8bf7\u8f93\u5165\u5b8c\u6574\u5305\u540d");

		cbBiz2.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12));
		cbBiz2.setSelected(true);
		cbBiz2.setText("\u751f\u6210\u4e1a\u52a1\u5c42\u4ee3\u7801");
		cbBiz2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cbBiz2ActionPerformed(evt);
			}
		});

		jLabel12.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12));
		jLabel12.setText("Package");

		txBiz2.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12));
		txBiz2.setText("com.orilore.biz");
		txBiz2.setToolTipText("\u8bf7\u8f93\u5165\u5b8c\u6574\u5305\u540d");

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout
				.setHorizontalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel3Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel3Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel3Layout
																										.createSequentialGroup()
																										.addContainerGap()
																										.addComponent(
																												jLabel11)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																												24,
																												Short.MAX_VALUE))
																						.addGroup(
																								jPanel3Layout
																										.createSequentialGroup()
																										.addContainerGap()
																										.addComponent(
																												jLabel10)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
																						.addGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								jPanel3Layout
																										.createSequentialGroup()
																										.addGroup(
																												jPanel3Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addGroup(
																																jPanel3Layout
																																		.createSequentialGroup()
																																		.addContainerGap()
																																		.addComponent(
																																				jLabel9,
																																				0,
																																				0,
																																				Short.MAX_VALUE))
																														.addComponent(
																																cbPojo1))
																										.addGap(2,
																												2,
																												2)))
																		.addGroup(
																				jPanel3Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(
																								txBiz1)
																						.addComponent(
																								txDao1)
																						.addComponent(
																								txPojo1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								182,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGap(39,
																				39,
																				39))
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addComponent(
																				cbBiz1)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				144,
																				Short.MAX_VALUE))
														.addComponent(cbDao1)
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addComponent(
																				jLabel12)
																		.addGap(26,
																				26,
																				26)
																		.addComponent(
																				txBiz2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				180,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addComponent(cbBiz2))
										.addContainerGap()));
		jPanel3Layout
				.setVerticalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addComponent(cbPojo1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel9)
														.addComponent(
																txPojo1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(cbDao1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel10)
																		.addGap(8,
																				8,
																				8)
																		.addComponent(
																				cbBiz1))
														.addComponent(
																txDao1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel11)
														.addComponent(
																txBiz1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(cbBiz2)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel12)
														.addComponent(
																txBiz2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap()));

		jTabbedPane1.addTab("MyBatis", jPanel3);

		javax.swing.GroupLayout jpOptionLayout = new javax.swing.GroupLayout(
				jpOption);
		jpOption.setLayout(jpOptionLayout);
		jpOptionLayout
				.setHorizontalGroup(jpOptionLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jpOptionLayout
										.createSequentialGroup()
										.addGroup(
												jpOptionLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jpOptionLayout
																		.createSequentialGroup()
																		.addGap(4,
																				4,
																				4)
																		.addGroup(
																				jpOptionLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel6)
																						.addComponent(
																								jLabel4,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								40,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jLabel5,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								34,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addGroup(
																				jpOptionLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								jpOptionLayout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.TRAILING,
																												false)
																										.addComponent(
																												txUrl,
																												javax.swing.GroupLayout.Alignment.LEADING)
																										.addComponent(
																												lstDB,
																												javax.swing.GroupLayout.Alignment.LEADING,
																												0,
																												236,
																												Short.MAX_VALUE))
																						.addGroup(
																								jpOptionLayout
																										.createSequentialGroup()
																										.addComponent(
																												txUid,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												69,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addGap(34,
																												34,
																												34)
																										.addComponent(
																												jLabel7,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												24,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addGap(18,
																												18,
																												18)
																										.addGroup(
																												jpOptionLayout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.TRAILING,
																																false)
																														.addComponent(
																																btnConnect,
																																javax.swing.GroupLayout.Alignment.LEADING,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																Short.MAX_VALUE)
																														.addComponent(
																																txPwd,
																																javax.swing.GroupLayout.Alignment.LEADING,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																91,
																																Short.MAX_VALUE))
																										.addGap(25,
																												25,
																												25))))
														.addGroup(
																jpOptionLayout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addGroup(
																				jpOptionLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(
																								jTabbedPane1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								282,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addGroup(
																								jpOptionLayout
																										.createSequentialGroup()
																										.addComponent(
																												btnSave,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												127,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addGap(5,
																												5,
																												5)
																										.addComponent(
																												btnCreate,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												Short.MAX_VALUE)))))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));
		jpOptionLayout
				.setVerticalGroup(jpOptionLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jpOptionLayout
										.createSequentialGroup()
										.addGroup(
												jpOptionLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel4)
														.addComponent(
																lstDB,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(12, 12, 12)
										.addGroup(
												jpOptionLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel5)
														.addComponent(
																txUrl,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												jpOptionLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel6)
														.addComponent(
																txUid,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel7)
														.addComponent(
																txPwd,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(btnConnect)
										.addGap(21, 21, 21)
										.addComponent(
												jTabbedPane1,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												245, Short.MAX_VALUE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jpOptionLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(btnSave)
														.addComponent(btnCreate))
										.addContainerGap()));

		spInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(
				javax.swing.BorderFactory.createEtchedBorder(),
				"\u63a7\u5236\u53f0",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
				javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 14)));

		txInfo.setBackground(javax.swing.UIManager.getDefaults().getColor(
				"Button.background"));
		txInfo.setColumns(20);
		txInfo.setEditable(false);
		txInfo.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12));
		txInfo.setRows(5);
		spInfo.setViewportView(txInfo);

		jLabel8.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12));
		jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel8.setText("\u79e6\u7687\u5c9b\u4e1c\u65b9\u7f57\u5c14\u9ad8\u7aef\u8f6f\u4ef6\u4eba\u624d\u5b9e\u8bad\u57fa\u5730");

		labUrl.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 12));
		labUrl.setForeground(new java.awt.Color(0, 51, 255));
		labUrl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		labUrl.setText("www.orilore.com");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel1Layout
										.createSequentialGroup()
										.addComponent(jLabel8)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												425, Short.MAX_VALUE)
										.addComponent(labUrl)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																labUrl,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(jLabel8))
										.addContainerGap()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		spTables,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		143,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		jpOption,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		313,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		spInfo,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		258,
																		Short.MAX_VALUE))
												.addComponent(
														jPanel1,
														javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE))
								.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(
														spInfo,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														466, Short.MAX_VALUE)
												.addComponent(
														jpOption,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(
														spTables,
														javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														466, Short.MAX_VALUE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jPanel1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void cbBizActionPerformed(java.awt.event.ActionEvent evt) {
		if(this.cbBiz.isSelected()){
			this.cbDao.setSelected(true);
		}
	}

	private void cbBiz2ActionPerformed(java.awt.event.ActionEvent evt) {
		if (cbBiz2.isSelected()) {
			this.cbBiz1.setSelected(true);
			this.cbDao1.setSelected(true);
		}
	}

	private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {
		JFileChooser jfc = new JFileChooser();
		File path = new File(System.getProperty("user.dir")+"\\src");
		jfc.setCurrentDirectory(path);
		jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
		jfc.showDialog(this, "ÉèÖÃ±£´æÂ·¾¶");
		try {
			this.path = jfc.getSelectedFile().getPath();
			txInfo.append("\n\rÎÄ¼þ´æ´¢Â·¾¶£º" + path + "\n\r");
		} catch (Exception e) {
		}
	}

	private void btnConnectActionPerformed(java.awt.event.ActionEvent evt) {
		this.url = this.txUrl.getText();
		this.uid = this.txUid.getText();
		this.pwd = this.txPwd.getText();
		if (driver.length() < 10) {
			this.txInfo.setText("ÇëÑ¡ÔñÊý¾Ý¿â");
			return;
		} else if (url.length() < 10) {
			this.txInfo.setText("ÇëÌîÐ´URL");
			return;
		} else if (uid.length() < 2) {
			this.txInfo.setText("ÇëÌîÐ´ÓÃ»§Ãû");
			return;
		} else if (pwd.length() < 2) {
			this.txInfo.setText("ÇëÌîÐ´ÃÜÂë");
			return;
		}
		this.getConnection();
		this.getTables();
	}

	private void lstDBActionPerformed(java.awt.event.ActionEvent evt) {
		String db = (String) this.lstDB.getSelectedItem();
		if (db.equals("MySQL")) {
			this.driver = "com.mysql.jdbc.Driver";
			this.txUrl.setText("jdbc:mysql://127.0.0.1:3306/test");
			this.txUid.setText("root");
			this.txPwd.setText("root");
			this.tables = "show tables";
		} else if (db.equals("Oracle")) {
			this.driver = "oracle.jdbc.driver.OracleDriver";
			this.txUrl.setText("jdbc:oracle:thin:@127.0.0.1:1521:orcl");
			this.txUid.setText("scott");
			this.txPwd.setText("tiger");
			this.tables = "select table_name from user_tables";
		}
	}

	private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {
		this.txInfo.setText("");
		if (this.path.length() < 5) {
			this.txInfo.setText("ÇëÑ¡ÔñÎÄ¼þ´æ´¢Â·¾¶!");
			return;
		}

		int k = this.jTabbedPane1.getSelectedIndex();
		if (k == 0) {
			String pa = txPojo.getText();
			String pb = txDao.getText();
			String pc = txBiz.getText();
			@SuppressWarnings("deprecation")
			Object tabNames[] = this.lstTables.getSelectedValues();

			if (tabNames == null || tabNames.length < 1) {
				this.txInfo.setText("ÇëÑ¡ÔñÊý¾Ý±í!");
				return;
			}

			if (pa.length() < 2) {
				this.txInfo.setText("ÇëÊäÈëPOJO°üÃû!");
				return;
			}

			String message = DBTool.createEntitys(path, conn, tabNames, pa);
			this.txInfo.append(message);

			if (this.cbDao.isSelected()) {
				if (pb.length() < 2) {
					this.txInfo.append("ÇëÊäÈëDAO°üÃû!");
					return;
				}
				
				message = DBTool.createDBUtil(path, conn, pb,this.driver,this.uid,this.pwd);
				this.txInfo.append(message);
				message = DBTool.createDaos(path, conn, tabNames, pb, pa);
				this.txInfo.append(message);
			}

			if (this.cbBiz.isSelected()) {
				if (pc.length() < 2) {
					this.txInfo.append("ÇëÊäÈëBIZ°üÃû!");
					return;
				}
				message = DBTool.createBizs(path, conn, tabNames, pc, pb, pa);
				this.txInfo.append(message);
			}
		} else {
			String pa = txPojo1.getText();
			String pb = txDao1.getText();
			String pc = txBiz1.getText();
			@SuppressWarnings("deprecation")
			Object tabNames[] = this.lstTables.getSelectedValues();
			Map<String, String> map = new HashMap<String, String>();
			map.put("driver", driver);
			map.put("url", url);
			map.put("uid", uid);
			map.put("pwd", pwd);

			if (tabNames == null || tabNames.length < 1) {
				this.txInfo.setText("ÇëÑ¡ÔñÊý¾Ý±í!");
				return;
			}

			if (pa.length() < 2) {
				this.txInfo.setText("ÇëÊäÈëPOJO°üÃû!");
				return;
			}
			String message = DBTool
					.createConfiguration(path, map, tabNames, pa);
			this.txInfo.append(message);

			message = DBTool.createEntitys(path, conn, tabNames, pa);

			this.txInfo.append(message);

			if (this.cbDao1.isSelected()) {
				if (pb.length() < 2) {
					this.txInfo.append("ÇëÊäÈëMapperÎÄ¼þ°üÃû!");
					return;
				}
				message = DBTool.createMapper(path, conn, tabNames, pa, pb,pc);
				this.txInfo.append(message);
			}

			if (this.cbBiz1.isSelected()) {
				if (pc.length() < 2) {
					this.txInfo.append("ÇëÊäÈëMapper½Ó¿Ú°üÃû!");
					return;
				}
				message = DBTool.createInterface(path,conn, tabNames, pa, pc);
				this.txInfo.append(message);
			}
			String pd = this.txBiz2.getText();
			if (this.cbBiz2.isSelected()) {
				if (pd.length() < 2) {
					this.txInfo.append("ÇëÊäÈëÒµÎñ²ã´úÂë°üÃû!");
					return;
				}
				message = DBTool.createMyBatisBizs(path, conn, tabNames, pd, pa, pc);
				this.txInfo.append(message);
			}
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		JFrame.setDefaultLookAndFeelDecorated(true);
		JDialog.setDefaultLookAndFeelDecorated(true);
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				FrameMain mf = new FrameMain();
				mf.setLocationRelativeTo(null);
				mf.setVisible(true);
				ImageIcon icon = new ImageIcon(this.getClass().getResource(
						"icon.jpg"));
				mf.setIconImage(icon.getImage());
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btnConnect;
	private javax.swing.JButton btnCreate;
	private javax.swing.JButton btnSave;
	private javax.swing.JCheckBox cbBiz;
	private javax.swing.JCheckBox cbBiz1;
	private javax.swing.JCheckBox cbBiz2;
	private javax.swing.JCheckBox cbDao;
	private javax.swing.JCheckBox cbDao1;
	private javax.swing.JCheckBox cbPojo;
	private javax.swing.JCheckBox cbPojo1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JTabbedPane jTabbedPane1;
	private javax.swing.JPanel jpOption;
	private javax.swing.JLabel labUrl;
	@SuppressWarnings("rawtypes")
	private javax.swing.JComboBox lstDB;
	@SuppressWarnings("rawtypes")
	private javax.swing.JList lstTables;
	private javax.swing.JScrollPane spInfo;
	private javax.swing.JScrollPane spTables;
	private javax.swing.JTextField txBiz;
	private javax.swing.JTextField txBiz1;
	private javax.swing.JTextField txBiz2;
	private javax.swing.JTextField txDao;
	private javax.swing.JTextField txDao1;
	private javax.swing.JTextArea txInfo;
	private javax.swing.JTextField txPojo;
	private javax.swing.JTextField txPojo1;
	private javax.swing.JTextField txPwd;
	private javax.swing.JTextField txUid;
	private javax.swing.JTextField txUrl;
	// End of variables declaration//GEN-END:variables
	private String path = "";
	private String[] dbs = { "ÇëÑ¡ÔñÊý¾Ý¿â", "MySQL", "Oracle" };
	private String driver = "";
	private String url = "";
	private String uid = "";
	private String pwd = "";
	private String tables = "";
	private Connection conn;
	private PreparedStatement ps;
	private ResultSet rs;

	public void getConnection() {
		try {
			Class.forName(driver);
			this.conn = DriverManager.getConnection(url, uid, pwd);
			this.txInfo.setText("Êý¾Ý¿âÁ¬½Ó³É¹¦£¡");
		} catch (Exception e) {
			this.txInfo.setText(e.getMessage());
		}
	}

	@SuppressWarnings("unchecked")
	public void getTables() {
		try {
			ps = conn.prepareStatement(tables);
			rs = ps.executeQuery();
			Vector<String> vc = new Vector<String>();
			while (rs.next()) {
				String name = rs.getString(1);
				vc.add(name);
			}
			this.lstTables.setListData(vc);
		} catch (Exception e) {
			this.txInfo.setText(e.getMessage());
		}
	}
}